workflows:
  android-build:  # <-- This is the workflow ID that must exist
    name: Android Build
    environment:
      vars:
        GRADLE_TASK: "assembleRelease"  # For APK
        # GRADLE_TASK: "bundleRelease"  # For AAB
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
    scripts:
      - name: Set up JDK 17
        script: |
          sudo apt-get update -y
          sudo apt-get install -y openjdk-17-jdk
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

      - name: Build with Gradle
        script: |
          ./gradlew $GRADLE_TASK
    artifacts:
      - app/build/outputs/apk/release/*.apk
      # - app/build/outputs/bundle/release/*.aab  # Uncomment for AAB
    publishing:
      email:
        recipients:
          - felixwprim@gmail.com 
